### ISSUE TITLE
If it's possible, PLEAAASE add camera stabilization and rotation

### ISSUE THREAD

**Issue by WaveSmashies** [HL2H0/WideEye#1]
With stabilization this mod would be perfect for content creation! If the camera was being smoothed by the game itself and not a post process like in videos online, it would avoid the issue of zooming and cropping losing some quality.

My head naturally sits rotated slightly to the right. It's not by much, but it comes across strongly in VR videos. I'd love to have the option to rotate it slightly left so it's more often correctly upright, again without needing to crop and zoom to hide it.

**Comment by HL2H0** [comment]
Thanks for the feedback! I’m considering stabilization for the 1.2.0 update—it would help maintain quality. I’ll also consider adding an option to adjust the camera’s rotation for better alignment.

**Comment by WaveSmashies** [comment]
> Thanks for the feedback! I’m considering stabilization for the 1.2.0 update—it would help maintain quality. I’ll also consider adding an option to adjust the camera’s rotation for better alignment.

WOOOOOOOOOOOOOOOOOO!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Best mod developer! My latest video would have looked a lot nicer with stabilization lol. I wish this mod came out sooner.

**Comment by HL2H0** [comment]
> With stabilization this mod would be perfect for content creation! If the camera was being smoothed by the game itself and not a post process like in videos online, it would avoid the issue of zooming and cropping losing some quality.
> 
> My head naturally sits rotated slightly to the right. It's not by much, but it comes across strongly in VR videos. I'd love to have the option to rotate it slightly left so it's more often correctly upright, again without needing to crop and zoom to hide it.

Done, Enjoy

**Comment by WaveSmashies** [comment]
Thank you so much!!!!!

If you wanna add me to your special thanks, I'd rather be credited as WaveSmash instead of WaveSmashies. I really appreciate it!
