### ISSUE TITLE
Position Offset

### ISSUE THREAD

**Issue by xDraxxis** [HL2H0/WideEye#4]
Rotation offset exists, being able to offset the position of the camera up/down/left/right as well would be very useful

**Comment by supersiv11** [comment]
does the mod work for u?

**Comment by xDraxxis** [comment]
> does the mod work for u?

Yep, make sure you're pressing "Find Camera" before altering settings, and it only applies to the PC spectator cam.

**Comment by HL2H0** [comment]
Thanks for the suggestion.
I'll look into adding it in the 1.3.0 update.

**Comment by HL2H0** [comment]
> Rotation offset exists, being able to offset the position of the camera up/down/left/right as well would be very useful

The feature had been implemented.
Thx for the suggestion !
