### ISSUE TITLE
Spectator Camera Post Process/Tonemapping Settings

### ISSUE THREAD

**Issue by xDraxxis** [HL2H0/WideEye#5]
Being able to swap from Neutral to ACES color space on the camera post-process would be amazing, some other settings might be nice too but not really as much as the tonemapping swap

**Comment by HL2H0** [comment]
Sorry for the late reply, I've been caught up with real-life stuff. 
Right now, the spectator camera post-FX profile in Bonelab doesn't support tonemapping, so I can't switch between Neutral and ACES color spaces. 

But that doesn't mean it can't be done. Maybe I just don't know everything the game can do.

But hey, version 2.0.0 is coming out soon, so keep an eye out for that!

**Comment by HL2H0** [comment]
The feature had been implemented as Post Processing Control but sadly Tonemapping isn't included.
