### ISSUE TITLE
Weird head rendering bug(maybe not caused by mod)

### ISSUE THREAD

**Issue by konradgl** [HL2H0/WideEye#7]
I have got a problem where the haed of every character has a weird rendering bug(see picture)
![Screenshot 2024-11-13 150154](https://github.com/user-attachments/assets/16ed1176-f839-42de-a180-4a51e8f64be7)

I'm btw on a quest 3 and this issue goes away when i press the menu button on my quest the head snaps back to the right positon and on some charcters is the head not even appearing except when i press the menu button like i already mentioned.

**Comment by HL2H0** [comment]
Hi Konradgl,  
This issue isn’t the mod’s fault; it's actually a problem with the game itself. BONELAB pushes your head back so it doesn't show up in the headset. 
To fix that, I'd suggest using [BodyTools by Fizzyhex.](https://mod.io/g/bonelab/m/body-tools)

**Comment by konradgl** [comment]
hey HL2H0 thx for the fast respond. i'll try that
