### ISSUE TITLE
feature request: silence non-error notifications

### ISSUE THREAD

**Issue by ThomasSteve83** [HL2H0/WideEye#8]
it's all in the title
seeing wideeye notifications on every level load is pretty immersion breaking and hurts video recording
yes, these notifications exist for good reason, but users should be able to turn them off somehow

**Comment by HL2H0** [comment]
Hey ThomasSteve83,

Yeah, I get it—those notifications can be pretty immersion-breaking, especially for recording. They're kinda important, but I totally agree that having a way to silence them is a must.

Thanks for the request! I'll make sure to add this in the next update.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Added a new preference to disable notifications and modified the SendNotfi method to check this preference before sending notifications.

You can review changes in this commit: https://github.com/mnmnk43434/HL2H0-WideEye-8/commit/53c2cd6b68bfcf34e7a5683905c13d0e166fb3a9.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by HL2H0** [comment]
The feature has been implemented. 
Thanks for the suggestion🤍
